---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-debug
  labels:
    app: ubuntu-debug
spec:
  containers:
  - image: eggshell/debug-pod
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu-debug
  restartPolicy: Always
